### ISSUE TITLE
increase_volume and decrease_volume does not work

### ISSUE THREAD

**Issue by csfreebird** [emacs-eaf/eaf-video-player#2]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.

**Describe the bug**
when using j or k key, get error message: 

![image](https://user-images.githubusercontent.com/870486/204721885-9dcb20f4-ae4b-47f0-adeb-8590ce7fcf6d.png)

in eaf buffer, find detail as following:
```
Traceback (most recent call last):
  File ".emacs.d/elpa/28.1/develop/eaf-20221110.2200/eaf.py", line 368, in eval_function
    getattr(buffer, function_name)()
  File ".emacs.d/elpa/28.1/develop/eaf-20221110.2200/core/utils.py", line 190, in wrapped_f
    return f(*args, **kwargs)
  File ".emacs.d/elpa/28.1/develop/eaf-20221110.2200/app/video-player/buffer.py", line 193, in decrease_volume
    self.media_player.setVolume(self.media_player.volume() - 10)
AttributeError: 'QMediaPlayer' object has no attribute 'setVolume'
```

**Additional context**
Ubuntu 22.04 , emacs 28.1

**Comment by manateelazycat** [comment]
Please update to newest version, has fixed, thanks for report.
